Part c
sobel121/ToDoListAlon pull request #3
Opened 2023-06-25 13:39 UTC by sobel121

2023-06-25 14:40 UTC, odev954 requested changes

2023-06-25 14:40 UTC, odev954 commented on domElementsHandler.js
> +        list: taskElement.children[0].children[0].checked ? "done" : "todo"};
utilsssssssssssssssssssssssssssssss

2023-06-25 14:40 UTC, odev954 commented on localStorageHandler.js
> +
empty line

2023-06-25 14:40 UTC, odev954 commented on localStorageHandler.js
> +    event.target.dataset.recentTaskDescription = event.target.value;
put `event.target` in variable

2023-06-25 14:40 UTC, odev954 commented on localStorageHandler.js
> +    const taskId = getTaskElementFromHisChildren(event.target).id;
>put `event.target` in variable

as  well

2023-06-25 14:40 UTC, odev954 commented on script.js
> +const getTaskElementFromHisChildren = (element) => {
check if you can solve the hover problem without searching the task div when hovering children.

2023-06-25 14:40 UTC, odev954 commented on script.js
> +                list.afterTask = createTaskObjectFromElement(afterTask);
move this to separate function

2023-06-25 14:40 UTC, odev954 commented on script.js
> +    const draggableElements = Object.values(list.children).filter(task => task.id !== dragged.id);
move to utils

2023-06-25 14:40 UTC, odev954 commented on script.js
> +const getDragAfterElement = (list, dragged, elementHeight) => {
rename this function

2023-06-25 14:40 UTC, odev954 commented on script.js
> +        const ElementBox = currentTask.getBoundingClientRect();
```suggestion
        const elementBox = currentTask.getBoundingClientRect();

```

2023-06-25 14:40 UTC, odev954 commented on script.js
> +
move all utillities to `utils.js`

2023-06-26 11:37 UTC, itayboop approved these changes

2023-06-26 11:37 UTC, itayboop commented on localStorageHandler.js
> +const RemoveAllListTasksFromLocalStorage = (listName) => {
why is it PascalCase?

2023-06-26 11:44 UTC, merged